#!/usr/bin/env python3
"""Convert a vi-recorder session into a EuRoC/ASL dataset tree."""

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from vir import Session  # noqa: E402

CAM_HEADER = "#timestamp [ns],filename"

# EuRoC reference values. These describe the EuRoC MAV's ADIS16448, not this phone.
EUROC_REFERENCE_NOISE = {
    "gyroscope_noise_density": "1.6968e-04",
    "gyroscope_random_walk": "1.9393e-05",
    "accelerometer_noise_density": "2.0000e-3",
    "accelerometer_random_walk": "3.0000e-3",
}

IDENTITY_T_BS = """T_BS:
  cols: 4
  rows: 4
  data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]"""


def rotate_intrinsics(w, h, fx, fy, cx, cy, deg):
    """Transform a pinhole model through a clockwise image rotation."""
    deg = deg % 360
    if deg == 0:
        return (w, h, fx, fy, cx, cy)
    if deg == 90:
        # (x, y) -> (H - y, x); the new x axis is the old y axis.
        return (h, w, fy, fx, h - cy, cx)
    if deg == 180:
        return (w, h, fx, fy, w - cx, h - cy)
    if deg == 270:
        # (x, y) -> (y, W - x)
        return (h, w, fy, fx, cy, w - cx)
    raise ValueError(f"rotation must be a multiple of 90, got {deg}")


def _camera_sensor_yaml(meta, w, h, fx, fy, cx, cy, fps, rotate, measured_hz):
    cam = meta.get("camera", {})
    skew = cam.get("rolling_shutter_skew_ns", 0)
    return f"""# EuRoC/ASL camera sensor description, generated by vi-recorder to_asl.py.
# UNCALIBRATED: pinhole intrinsics from Android metadata, zero distortion, identity T_BS.
# Rotated {rotate} deg clockwise; measured rate {measured_hz:.2f} Hz; rolling shutter skew {skew} ns.
sensor_type: camera
comment: monocular camera, uncalibrated intrinsics
{IDENTITY_T_BS}
rate_hz: {fps}
resolution: [{w}, {h}]
camera_model: pinhole
intrinsics: [{fx}, {fy}, {cx}, {cy}]
distortion_model: radial-tangential
distortion_coefficients: [0.0, 0.0, 0.0, 0.0]
"""


def _imu_sensor_yaml(meta):
    imu = meta.get("imu", {})
    achieved = float(imu.get("achieved_rate_hz", 0.0))
    # nominal rate, not the measured one
    rate = int(imu.get("requested_rate_hz") or round(achieved) or 200)
    noise = "\n".join(f"{k}: {v}" for k, v in EUROC_REFERENCE_NOISE.items())
    return f"""# EuRoC/ASL IMU sensor description, generated by vi-recorder to_asl.py.
# UNCALIBRATED: EuRoC ADIS16448 noise values; measured rate {achieved:.2f} Hz.
sensor_type: imu
comment: {imu.get('gyro_name', 'gyroscope')} / {imu.get('accel_name', 'accelerometer')}
{IDENTITY_T_BS}
rate_hz: {rate}
{noise}
"""


def _body_yaml():
    return f"""# EuRoC/ASL body description, generated by vi-recorder to_asl.py.
comment: body frame, coincident with the IMU
sensor_type: body
{IDENTITY_T_BS}
"""


def convert(session_dir, out_dir, rotate=0, png=False, limit=None):
    """Writes an ASL tree. Returns a small report dict."""
    if rotate % 90 != 0:
        raise ValueError(f"rotation must be a multiple of 90, got {rotate}")
    rotate %= 360

    session = Session(session_dir)
    out = Path(out_dir)
    mav0 = out / "mav0"
    if mav0.exists():
        raise FileExistsError(f"{mav0} already exists; refusing to overwrite")

    data_dir = mav0 / "cam0" / "data"
    data_dir.mkdir(parents=True)
    (mav0 / "imu0").mkdir(parents=True)

    meta = session.metadata
    cam = meta.get("camera", {})
    src_w = int(cam.get("configured_width") or meta.get("config", {}).get("width", 640))
    src_h = int(cam.get("configured_height") or meta.get("config", {}).get("height", 480))

    focal = float(cam.get("focal_length_mm") or 0.0)
    sw = float(cam.get("sensor_width_mm") or 0.0)
    sh = float(cam.get("sensor_height_mm") or 0.0)
    fx = round(focal / sw * src_w, 6) if sw else 0.0
    fy = round(focal / sh * src_h, 6) if sh else 0.0
    cx, cy = src_w / 2.0, src_h / 2.0

    w, h, fx, fy, cx, cy = rotate_intrinsics(src_w, src_h, fx, fy, cx, cy, rotate)

    # target format follows the source unless --png forces a transcode
    src_is_png = str(meta.get("config", {}).get("encoding", "JPEG")).upper() == "PNG"
    target_png = png or src_is_png
    need_decode = rotate != 0 or (png and not src_is_png)
    if need_decode:
        from io import BytesIO

        from PIL import Image

    ext = "png" if target_png else "jpg"
    cam_rows, stamps = [CAM_HEADER], []
    written = 0

    for rec, blob in session.iter_frame_bytes():
        if limit is not None and written >= limit:
            break
        ts = rec["ts_ns"]
        name = f"{ts}.{ext}"
        target = data_dir / name

        if need_decode:
            img = Image.open(BytesIO(blob)).convert("RGB" if session.is_color else "L")
            if rotate:
                # PIL rotates counter-clockwise, so negate for a clockwise turn.
                img = img.rotate(-rotate, expand=True)
            if target_png:
                img.save(target, format="PNG")
            else:
                img.save(target, format="JPEG", quality=95)
        else:
            target.write_bytes(blob)

        cam_rows.append(f"{ts},{name}")
        stamps.append(str(ts))
        written += 1

    (mav0 / "cam0" / "data.csv").write_text("\n".join(cam_rows) + "\n")
    (out / "timestamps.txt").write_text("\n".join(stamps) + "\n")

    shutil.copyfile(session.root / "imu.csv", mav0 / "imu0" / "data.csv")
    imu_samples = sum(
        1 for line in (mav0 / "imu0" / "data.csv").read_text().splitlines()
        if line.strip() and not line.startswith("#")
    )

    fps = int(meta.get("config", {}).get("fps", 30))
    measured_hz = 0.0
    if len(stamps) > 1:
        span = int(stamps[-1]) - int(stamps[0])
        measured_hz = (len(stamps) - 1) * 1e9 / span if span > 0 else 0.0
    (mav0 / "cam0" / "sensor.yaml").write_text(
        _camera_sensor_yaml(meta, w, h, fx, fy, cx, cy, fps, rotate, measured_hz))
    (mav0 / "imu0" / "sensor.yaml").write_text(_imu_sensor_yaml(meta))
    (mav0 / "body.yaml").write_text(_body_yaml())

    return {
        "frames": written,
        "imu_samples": imu_samples,
        "resolution": [w, h],
        "intrinsics": [fx, fy, cx, cy],
        "rotate": rotate,
        "encoding": ext,
        "measured_hz": round(measured_hz, 2),
        "nominal_hz": fps,
        "frames_dropped": int(meta.get("session", {}).get("frames_dropped", 0)),
        "out": str(out),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("session", type=Path)
    ap.add_argument("outdir", type=Path)
    ap.add_argument("--rotate", type=int, default=0, choices=[0, 90, 180, 270],
                    help="clockwise rotation applied to images AND intrinsics")
    ap.add_argument("--png", action="store_true",
                    help="transcode to PNG (strict EuRoC); slower and larger, recovers no quality")
    ap.add_argument("--limit", type=int, default=None, help="convert only the first N frames")
    args = ap.parse_args()

    rep = convert(args.session, args.outdir, rotate=args.rotate, png=args.png, limit=args.limit)
    print(f"wrote {rep['out']}")
    for k in ("frames", "imu_samples", "resolution", "intrinsics", "rotate", "encoding"):
        print(f"  {k}: {rep[k]}")
    print(f"  rate: {rep['measured_hz']} Hz measured vs {rep['nominal_hz']} Hz nominal")

    dropped = rep["frames_dropped"]
    total = rep["frames"] + dropped
    if total and dropped / total >= 0.05:
        print(f"\n  WARNING: {dropped} of {total} frames ({100*dropped/total:.0f}%) were")
        print("  dropped during recording. The sequence has real gaps; a monocular-inertial")
        print("  estimator may fail to initialise or lose tracking across them.")

    print("\n  Intrinsics are UNCALIBRATED and T_BS is identity. Calibrate with Kalibr")
    print("  before using this dataset for anything quantitative.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
